@startuml
'https://plantuml.com/class-diagram

class PlayerData{
    int thoiGian, soLuotChoi, diem
}
class DashBoard{}
interface PlayerDataListener{
    void listen(PlayerData playerdata)
}

DashBoard --|> PlayerDataListener

@enduml