// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIXMVQRhYutXfxT0WXrLOE9UIkEKjp9CQ',
    appId: '1:964725434305:web:4030d8b1ca60bbf655b140',
    messagingSenderId: '964725434305',
    projectId: 'tiendat-firebase-d1499',
    authDomain: 'tiendat-firebase-d1499.firebaseapp.com',
    storageBucket: 'tiendat-firebase-d1499.appspot.com',
    measurementId: 'G-E33HWDLTVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBca5GhbJSJdBxjz2Jg9q8xSRxcphJGmBM',
    appId: '1:964725434305:android:45c794494a68d02c55b140',
    messagingSenderId: '964725434305',
    projectId: 'tiendat-firebase-d1499',
    storageBucket: 'tiendat-firebase-d1499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtH3MtdmaEw5sXjx5TXmGPEmesrjy7JU',
    appId: '1:964725434305:ios:571951e470d28ec555b140',
    messagingSenderId: '964725434305',
    projectId: 'tiendat-firebase-d1499',
    storageBucket: 'tiendat-firebase-d1499.appspot.com',
    iosBundleId: 'com.example.tiendatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUtH3MtdmaEw5sXjx5TXmGPEmesrjy7JU',
    appId: '1:964725434305:ios:571951e470d28ec555b140',
    messagingSenderId: '964725434305',
    projectId: 'tiendat-firebase-d1499',
    storageBucket: 'tiendat-firebase-d1499.appspot.com',
    iosBundleId: 'com.example.tiendatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIXMVQRhYutXfxT0WXrLOE9UIkEKjp9CQ',
    appId: '1:964725434305:web:db57596f60950ca355b140',
    messagingSenderId: '964725434305',
    projectId: 'tiendat-firebase-d1499',
    authDomain: 'tiendat-firebase-d1499.firebaseapp.com',
    storageBucket: 'tiendat-firebase-d1499.appspot.com',
    measurementId: 'G-14TKLMSDZB',
  );
}
